import React, { useEffect, useMemo, useState } from 'react';
import { getDashboardSummary, getDiagnostics, getTaskEvents, cancelTask, retryTask } from './api/dashboard';
import { createTask, getTasks, getTask } from './api/tasks';
import { apiRequest } from './api/client';
import './styles/global.css';

const NAV = [
  ['overview', '⌂', 'Overview'], ['tasks', '✓', 'Tasks'], ['agents', '◈', 'Agents'],
  ['workers', '▣', 'Workers'], ['executions', '◷', 'Executions'], ['logs', '≡', 'Logs'],
  ['monitoring', '⌁', 'Monitoring'], ['models', '◇', 'Models'], ['tools', '⚒', 'Tools'],
  ['diagnostics', '⊙', 'Diagnostics'], ['settings', '⚙', 'Settings'],
];
const STATUS = ['all', 'queued', 'running', 'completed', 'failed', 'cancelled'];
const translations = {
  en: { overview: 'Overview', tasks: 'Tasks', agents: 'Agents', workers: 'Workers', executions: 'Executions', logs: 'Logs', monitoring: 'Monitoring', models: 'Models', tools: 'Tools', diagnostics: 'Diagnostics', settings: 'Settings', search: 'Search tasks, IDs…', run: 'Run task', create: 'Create', taskPlaceholder: 'Describe a task for the agent…', recent: 'Recent activity', activity: 'Live activity', workerHealth: 'Worker health', systemHealth: 'System health', total: 'Total tasks', queued: 'Queued', running: 'Running', completed: 'Completed', failed: 'Failed', cancelled: 'Cancelled', avg: 'Average execution', success: 'Success rate', noTasks: 'No tasks found.', noWorkers: 'No workers registered.', refresh: 'Refresh', connected: 'Connected', unavailable: 'Not exposed by backend', realData: 'REAL DATA', source: 'Backend source of truth', cancel: 'Cancel', retry: 'Retry', detail: 'Task detail', execution: 'Execution', evidence: 'Execution evidence', verified: 'Verified', notVerified: 'Not verified', model: 'Model', status: 'Status', created: 'Created', started: 'Started', finished: 'Finished', duration: 'Duration', worker: 'Worker', command: 'Command', filters: 'Filters', system: 'System', backend: 'Backend', database: 'Database', agent: 'Agent', health: 'Health', theme: 'Theme', language: 'Language', connection: 'Connection', dark: 'Dark', light: 'Light', systemTheme: 'System', english: 'English', persian: 'Persian', noEvents: 'No activity recorded yet.', noDiagnostics: 'Diagnostics have not been loaded.', unsupported: 'This capability is not currently exposed by the backend. The dashboard intentionally does not fabricate controls or data.', toolsNote: 'Tool execution and permissions remain enforced by the backend agent runtime.', modelsNote: 'Only model information reported by the runtime is shown here.', workerNote: 'Worker telemetry is shown only when the configured worker reports it.', agentNote: 'Agent state is derived from the real worker/runtime health endpoint.', settingsNote: 'Only local presentation settings are editable from this dashboard. Deployment and security settings remain backend-owned.', retryable: 'Failed tasks can be requeued through the real retry API.',
  },
  fa: { overview: 'نمای کلی', tasks: 'تسک‌ها', agents: 'ایجنت‌ها', workers: 'ورکرها', executions: 'اجراها', logs: 'لاگ‌ها', monitoring: 'مانیتورینگ', models: 'مدل‌ها', tools: 'ابزارها', diagnostics: 'عیب‌یابی', settings: 'تنظیمات', search: 'جستجوی تسک و شناسه…', run: 'اجرای تسک', create: 'ایجاد', taskPlaceholder: 'تسک موردنظر برای ایجنت را بنویسید…', recent: 'فعالیت اخیر', activity: 'فعالیت زنده', workerHealth: 'سلامت ورکر', systemHealth: 'سلامت سیستم', total: 'کل تسک‌ها', queued: 'در صف', running: 'در حال اجرا', completed: 'تکمیل‌شده', failed: 'ناموفق', cancelled: 'لغوشده', avg: 'میانگین زمان اجرا', success: 'نرخ موفقیت', noTasks: 'تسکی پیدا نشد.', noWorkers: 'ورکری ثبت نشده است.', refresh: 'به‌روزرسانی', connected: 'متصل', unavailable: 'در Backend ارائه نشده', realData: 'داده واقعی', source: 'منبع حقیقت: Backend', cancel: 'لغو', retry: 'تلاش مجدد', detail: 'جزئیات تسک', execution: 'اجرا', evidence: 'شواهد اجرا', verified: 'تأییدشده', notVerified: 'تأییدنشده', model: 'مدل', status: 'وضعیت', created: 'ایجاد', started: 'شروع', finished: 'پایان', duration: 'مدت', worker: 'ورکر', command: 'فرمان', filters: 'فیلترها', system: 'سیستم', backend: 'Backend', database: 'دیتابیس', agent: 'ایجنت', health: 'سلامت', theme: 'تم', language: 'زبان', dark: 'تیره', light: 'روشن', systemTheme: 'سیستم', english: 'English', persian: 'فارسی', noEvents: 'هنوز فعالیتی ثبت نشده است.', noDiagnostics: 'عیب‌یابی هنوز بارگذاری نشده است.', unsupported: 'این قابلیت فعلاً توسط Backend ارائه نشده است. داشبورد عمداً داده یا کنترل جعلی نمایش نمی‌دهد.', toolsNote: 'اجرای ابزارها و سطح دسترسی آن‌ها توسط Runtime واقعی Backend کنترل می‌شود.', modelsNote: 'فقط اطلاعات مدل‌هایی که Runtime واقعی گزارش می‌کند نمایش داده می‌شود.', workerNote: 'تله‌متری فقط زمانی نمایش داده می‌شود که ورکر واقعی آن را گزارش کند.', agentNote: 'وضعیت ایجنت از endpoint سلامت واقعی Runtime/Worker گرفته می‌شود.', settingsNote: 'فقط تنظیمات ظاهری محلی از داشبورد قابل تغییر است؛ تنظیمات امنیتی و Deployment در اختیار Backend است.', retryable: 'تسک‌های ناموفق از طریق API واقعی قابل قرار دادن مجدد در صف هستند.', },
};

const tone = (s) => ({ completed: 'success', running: 'info', queued: 'warning', failed: 'danger', cancelled: 'muted', online: 'success', ready: 'success', pass: 'success', ok: 'success', connected: 'success' }[String(s || '').toLowerCase()] || 'muted');
const dateTime = (v) => v ? new Date(Number(v) * 1000).toLocaleString() : '—';
const duration = (task) => task?.started_at && task?.completed_at ? `${Math.max(0, task.completed_at - task.started_at).toFixed(1)}s` : '—';
const shortId = (id) => String(id || '').slice(0, 12);

function Badge({ value }) { return <span className={`badge ${tone(value)}`}><i />{String(value || 'unknown').toUpperCase()}</span>; }
function Card({ title, action, children, className = '' }) { return <section className={`card ${className}`}><div className="card-title"><h2>{title}</h2>{action}</div>{children}</section>; }
function Empty({ children }) { return <div className="empty">{children}</div>; }
function Metric({ label, value, accent }) { return <div className={`metric ${accent || ''}`}><span>{label}</span><strong>{value ?? '—'}</strong></div>; }
function StatusLine({ label, value }) { return <div className="status-line"><span>{label}</span><Badge value={value} /></div>; }

function TaskTable({ tasks, onOpen, t }) {
  if (!tasks.length) return <Empty>{t.noTasks}</Empty>;
  return <div className="table-wrap"><table><thead><tr><th>{t.tasks}</th><th>{t.status}</th><th>{t.model}</th><th>{t.created}</th><th>{t.duration}</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id} tabIndex="0" onClick={() => onOpen(task.id)} onKeyDown={(e) => e.key === 'Enter' && onOpen(task.id)}><td><strong>{shortId(task.id)}</strong><small>{task.prompt}</small></td><td><Badge value={task.status} /></td><td>{task.model || 'Default'}</td><td>{dateTime(task.created_at)}</td><td>{duration(task)}</td></tr>)}</tbody></table></div>;
}

function Activity({ events, t }) {
  if (!events?.length) return <Empty>{t.noEvents}</Empty>;
  return <div className="activity-list">{events.map((event, index) => <div className="activity-item" key={`${event.id || event.created_at}-${index}`}><div className="activity-dot" /><div className="activity-main"><div><strong>{String(event.event_type || event.type || 'event').replaceAll('_', ' ')}</strong><time>{dateTime(event.created_at || event.timestamp)}</time></div><small>{event.task_id ? shortId(event.task_id) : ''}{event.status ? ` · ${event.status}` : ''}{event.detail ? ` · ${typeof event.detail === 'string' ? event.detail : JSON.stringify(event.detail)}` : ''}</small></div></div>)}</div>;
}

function Workers({ workers, t }) {
  if (!workers?.length) return <Empty>{t.noWorkers}</Empty>;
  return <div className="worker-list">{workers.map((worker) => { const health = worker.health || {}; return <div className="worker-card" key={worker.worker_id}><div className="worker-head"><div><strong>{worker.worker_id}</strong><small>{worker.host}:{worker.port}</small></div><Badge value={worker.status} /></div><div className="worker-stats"><span>CPU <b>{health.cpu_percent ?? '—'}%</b></span><span>RAM <b>{health.ram_percent ?? '—'}%</b></span><span>GPU <b>{health.gpu_percent ?? '—'}%</b></span></div><div className="worker-foot"><span>{health.ollama_status ? `Ollama: ${health.ollama_status}` : t.workerNote}</span>{health.last_heartbeat && <time>{dateTime(health.last_heartbeat)}</time>}</div></div>; })}</div>;
}

function TaskDrawer({ task, events, onClose, onMutate, busy, t }) {
  if (!task) return null;
  const evidence = task.result?.execution_evidence || task.result?.evidence || task.metadata?.execution_evidence;
  const verified = evidence?.verified;
  return <div className="drawer-backdrop" role="presentation" onClick={onClose}><aside className="drawer" role="dialog" aria-modal="true" aria-label={t.detail} onClick={(e) => e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">{t.detail}</span><h2>{task.id}</h2></div><button className="icon-btn" onClick={onClose} aria-label="Close">×</button></div><div className="drawer-status"><Badge value={task.status} /><span>{task.model || 'Default model'}</span></div><div className="prompt-block">{task.prompt}</div><div className="detail-grid"><Detail label={t.created} value={dateTime(task.created_at)} /><Detail label={t.started} value={dateTime(task.started_at)} /><Detail label={t.finished} value={dateTime(task.completed_at)} /><Detail label={t.duration} value={duration(task)} /><Detail label={t.model} value={task.model || 'Default'} /><Detail label={t.command} value={task.metadata?.command || 'agent.execute'} /></div>{task.error && <div className="error-box">{task.error}</div>}<div className="section-label">{t.execution}</div><div className="timeline">{events?.map((event) => <div key={event.id}><span>{dateTime(event.created_at)}</span><strong>{String(event.event_type || 'event').replaceAll('_', ' ')}</strong><small>{event.status || ''}{event.detail ? ` · ${typeof event.detail === 'string' ? event.detail : JSON.stringify(event.detail)}` : ''}</small></div>)}</div><div className="section-label">{t.evidence}</div><div className={`evidence ${verified === true ? 'verified' : verified === false ? 'not-verified' : ''}`}><strong>{verified === true ? `✓ ${t.verified}` : verified === false ? `✕ ${t.notVerified}` : 'Evidence not reported'}</strong>{evidence && <pre>{JSON.stringify(evidence, null, 2)}</pre>}</div><div className="drawer-actions">{['queued', 'running'].includes(task.status) && <button disabled={busy} onClick={() => onMutate(cancelTask, task.id)}>{t.cancel}</button>}{task.status === 'failed' && <button disabled={busy} onClick={() => onMutate(retryTask, task.id)}>{t.retry}</button>}</div><details><summary>Raw execution result</summary><pre>{JSON.stringify(task.result, null, 2)}</pre></details></aside></div>;
}
function Detail({ label, value }) { return <div><small>{label}</small><strong>{value || '—'}</strong></div>; }

function Diagnostics({ value, loading, t }) {
  if (loading) return <Card title={t.diagnostics}><div className="skeleton-stack"><div /><div /><div /></div></Card>;
  return <Card title={t.diagnostics}>{value?.checks?.length ? <div className="diagnostic-list">{value.checks.map((check) => <div key={check.name}><div><strong>{check.name}</strong><small>{typeof check.detail === 'string' ? check.detail : JSON.stringify(check.detail)}</small></div><Badge value={check.status} /></div>)}</div> : <Empty>{t.noDiagnostics}</Empty>}</Card>;
}

export default function App() {
  const [page, setPage] = useState(window.location.hash.replace('#/', '') || 'overview');
  const [summary, setSummary] = useState(null); const [tasks, setTasks] = useState([]); const [selected, setSelected] = useState(null); const [events, setEvents] = useState([]); const [diagnostics, setDiagnostics] = useState(null); const [diagnosticLoading, setDiagnosticLoading] = useState(false); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [theme, setTheme] = useState(localStorage.getItem('agent-theme') || 'dark'); const [lang, setLang] = useState(localStorage.getItem('agent-lang') || 'en'); const t = translations[lang] || translations.en;
  const workers = summary?.workers?.workers || []; const agent = summary?.agent || {}; const counts = summary?.tasks?.counts || {};
  const terminal = (counts.completed || 0) + (counts.failed || 0) + (counts.cancelled || 0); const successRate = terminal ? `${Math.round((counts.completed || 0) / terminal * 100)}%` : '—';
  const visibleTasks = useMemo(() => tasks.filter((task) => (filter === 'all' || task.status === filter) && `${task.id} ${task.prompt} ${task.model || ''}`.toLowerCase().includes(query.toLowerCase())), [tasks, filter, query]);

  const refresh = async () => { try { const [s, list] = await Promise.all([getDashboardSummary(), getTasks()]); setSummary(s); setTasks(list?.tasks || []); setError(''); } catch (e) { setError(e.message); } };
  const loadDiagnostics = async () => { setDiagnosticLoading(true); try { setDiagnostics(await getDiagnostics()); setError(''); } catch (e) { setError(e.message); } finally { setDiagnosticLoading(false); } };
  useEffect(() => { const onHash = () => setPage(window.location.hash.replace('#/', '') || 'overview'); window.addEventListener('hashchange', onHash); refresh(); const id = setInterval(refresh, 5000); return () => { window.removeEventListener('hashchange', onHash); clearInterval(id); }; }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.dir = lang === 'fa' ? 'rtl' : 'ltr'; document.documentElement.lang = lang; localStorage.setItem('agent-theme', theme); localStorage.setItem('agent-lang', lang); }, [theme, lang]);
  useEffect(() => { if (page === 'diagnostics' && !diagnostics) loadDiagnostics(); }, [page]);
  async function openTask(id) { try { const [task, eventData] = await Promise.all([getTask(id), getTaskEvents(id)]); setSelected(task); setEvents(eventData?.events || []); } catch (e) { setError(e.message); } }
  async function mutate(fn, id) { setBusy(true); try { await fn(id); await refresh(); await openTask(id); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function submit(e) { e.preventDefault(); const form = e.currentTarget; const prompt = new FormData(form).get('prompt')?.toString().trim(); if (!prompt) return; setBusy(true); try { await createTask({ prompt }); form.reset(); await refresh(); setPage('tasks'); window.location.hash = '#/tasks'; } catch (e) { setError(e.message); } finally { setBusy(false); } }
  const go = (target) => { setPage(target); window.location.hash = `#/${target}`; };

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">AI</div><div><strong>Agent Platform</strong><small>Autonomous Control Center</small></div></div><nav aria-label="Main navigation">{NAV.map(([key, icon, label]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => go(key)}><span>{icon}</span><b>{t[key] || label}</b></button>)}</nav><div className="sidebar-foot"><Badge value={summary?.system?.ready?.status} /><small>{t.source}</small></div></aside>
    <main className="main"><header className="topbar"><div><span className="eyebrow">CONTROL PLANE · {t.realData}</span><h1>{t[page] || page}</h1></div><div className="top-actions"><label className="search">⌕<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t.search} aria-label={t.search} /></label><button className="icon-btn" onClick={refresh} aria-label={t.refresh}>↻</button><select value={lang} onChange={(e) => setLang(e.target.value)} aria-label={t.language}><option value="en">EN</option><option value="fa">FA</option></select><select value={theme} onChange={(e) => setTheme(e.target.value)} aria-label={t.theme}><option value="dark">{t.dark}</option><option value="light">{t.light}</option><option value="system">{t.systemTheme}</option></select></div></header>
      {error && <div className="alert danger" role="alert">⚠ <span>{error}</span><button onClick={() => setError('')} aria-label="Dismiss">×</button></div>}
      {page === 'overview' && <><form className="hero-command" onSubmit={submit}><div><span className="eyebrow">AUTONOMOUS EXECUTION</span><h2>One control plane for the real agent runtime.</h2><p>{t.source}. Tasks are persisted, executed by the configured worker and only completed with observable evidence.</p></div><div className="command-row"><input name="prompt" required placeholder={t.taskPlaceholder} /><button disabled={busy}>{busy ? '…' : t.run}</button></div></form><div className="status-strip"><StatusLine label={t.system} value={summary?.system?.live?.status} /><StatusLine label={t.backend} value={summary?.system?.ready?.status} /><StatusLine label={t.agent} value={agent.status} /><StatusLine label={t.worker} value={workers[0]?.status} /></div><div className="metrics"><Metric label={t.total} value={counts.total} /><Metric label={t.queued} value={counts.queued} /><Metric label={t.running} value={counts.running} /><Metric label={t.completed} value={counts.completed} accent="success" /><Metric label={t.failed} value={counts.failed} accent="danger" /><Metric label={t.cancelled} value={counts.cancelled} /><Metric label={t.avg} value={summary?.tasks?.average_execution_seconds != null ? `${Number(summary.tasks.average_execution_seconds).toFixed(1)}s` : '—'} /><Metric label={t.success} value={successRate} accent="success" /></div><div className="dashboard-grid"><Card title={t.recent}><TaskTable tasks={tasks.slice(0, 8)} onOpen={openTask} t={t} /></Card><Card title={t.workerHealth}><Workers workers={workers} t={t} /></Card></div><div className="dashboard-grid lower"><Card title={t.activity}><Activity events={summary?.tasks?.recent_events || []} t={t} /></Card><Card title={t.systemHealth}><div className="health-panel"><StatusLine label={t.backend} value={summary?.system?.live?.status} /><StatusLine label={t.database} value={summary?.system?.ready?.status} /><StatusLine label={t.agent} value={agent.status} /><StatusLine label={t.worker} value={workers[0]?.status} /></div></Card></div></>}
      {page === 'tasks' && <><div className="page-toolbar"><div className="filters" aria-label={t.filters}>{STATUS.map((value) => <button key={value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{value}</button>)}</div><form className="quick-create" onSubmit={submit}><input name="prompt" required placeholder={t.taskPlaceholder} /><button disabled={busy}>{t.create}</button></form></div><Card title={`${visibleTasks.length} ${t.tasks}`}><TaskTable tasks={visibleTasks} onOpen={openTask} t={t} /></Card></>}
      {page === 'agents' && <div className="dashboard-grid"><Card title={t.agents}><div className="agent-card"><div className="agent-orb">AI</div><div><Badge value={agent.status} /><h2>{agent.worker?.worker_id || agent.worker_id || 'Agent runtime'}</h2><p>{t.agentNote}</p></div></div><div className="detail-grid"><Detail label={t.status} value={agent.status} /><Detail label={t.worker} value={agent.worker?.worker_id || agent.worker_id} /><Detail label={t.model} value={agent.model || agent.worker?.model} /></div></Card><Card title={t.activity}><Activity events={summary?.tasks?.recent_events || []} t={t} /></Card></div>}
      {page === 'workers' && <Card title={t.workers}><p className="muted">{t.workerNote}</p><Workers workers={workers} t={t} /></Card>}
      {page === 'executions' && <Card title={t.executions}><TaskTable tasks={tasks.filter((task) => task.started_at)} onOpen={openTask} t={t} /></Card>}
      {page === 'logs' && <Card title={t.logs}><div className="log-toolbar"><span className="muted">{t.realData}</span><button className="secondary" onClick={refresh}>{t.refresh}</button></div><Activity events={summary?.tasks?.recent_events || []} t={t} /></Card>}
      {page === 'monitoring' && <div className="dashboard-grid"><Card title={t.systemHealth}><div className="health-panel"><StatusLine label={t.backend} value={summary?.system?.live?.status} /><StatusLine label={t.database} value={summary?.system?.ready?.status} /><StatusLine label={t.agent} value={agent.status} /><StatusLine label={t.worker} value={workers[0]?.status} /></div><div className="monitor-kpis"><Metric label={t.total} value={counts.total} /><Metric label={t.avg} value={summary?.tasks?.average_execution_seconds != null ? `${Number(summary.tasks.average_execution_seconds).toFixed(1)}s` : '—'} /><Metric label={t.success} value={successRate} /></div></Card><Card title={t.workers}><Workers workers={workers} t={t} /></Card></div>}
      {page === 'models' && <Card title={t.models}><div className="capability"><div className="capability-icon">◇</div><div><Badge value={agent.model ? 'available' : 'unknown'} /><h2>{agent.model || agent.worker?.model || 'Model not reported'}</h2><p>{t.modelsNote}</p></div></div></Card>}
      {page === 'tools' && <Card title={t.tools}><div className="capability"><div className="capability-icon">⚒</div><div><Badge value="backend-enforced" /><h2>Backend Tool Registry</h2><p>{t.toolsNote}</p><p className="muted">{t.unsupported}</p></div></div></Card>}
      {page === 'diagnostics' && <Diagnostics value={diagnostics} loading={diagnosticLoading} t={t} />}
      {page === 'settings' && <div className="dashboard-grid"><Card title={t.theme}><Setting label={t.theme}><select value={theme} onChange={(e) => setTheme(e.target.value)}><option value="dark">{t.dark}</option><option value="light">{t.light}</option><option value="system">{t.systemTheme}</option></select></Setting><Setting label={t.language}><select value={lang} onChange={(e) => setLang(e.target.value)}><option value="en">{t.english}</option><option value="fa">{t.persian}</option></select></Setting></Card><Card title={t.connection}><p className="muted">{t.settingsNote}</p><div className="connection-chip">API · <code>VITE_API_BASE_URL</code></div></Card></div>}
    </main><TaskDrawer task={selected} events={events} onClose={() => setSelected(null)} onMutate={mutate} busy={busy} t={t} /></div>;
}
function Setting({ label, children }) { return <div className="setting"><span>{label}</span>{children}</div>; }
