import React, { useEffect, useMemo, useState } from 'react';
import { apiRequest } from './api/client';
import { getDashboardSummary, getDiagnostics, getTaskEvents, cancelTask, retryTask, createTask, getTasks, getTask } from './api/dashboard';
import './styles/global.css';

const NAV = [['overview','⌂','Overview'],['tasks','✓','Tasks'],['agents','◈','Agents'],['workers','▣','Workers'],['executions','◷','Executions'],['logs','≡','Logs'],['monitoring','⌁','Monitoring'],['models','◇','Models'],['tools','⚒','Tools'],['diagnostics','⊙','Diagnostics'],['settings','⚙','Settings']];
const tone=s=>({completed:'success',running:'info',queued:'warning',failed:'danger',cancelled:'muted',online:'success',ready:'success',pass:'success'}[String(s||'').toLowerCase()]||'muted');
const time=v=>v?new Date(v*1000).toLocaleString():'—';
const dur=t=>t.started_at&&t.completed_at?`${Math.max(0,t.completed_at-t.started_at).toFixed(1)}s`:'—';
function Badge({value}){return <span className={`badge ${tone(value)}`}><i/>{String(value||'unknown').toUpperCase()}</span>}
function Card({title,children,action}){return <section className="card"><div className="card-title"><h2>{title}</h2>{action}</div>{children}</section>}
function Empty({children}){return <div className="empty">{children}</div>}
function TaskTable({tasks,onOpen}){if(!tasks.length)return <Empty>No tasks found.</Empty>;return <div className="table-wrap"><table><thead><tr><th>Task</th><th>Status</th><th>Model</th><th>Created</th><th>Duration</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id} onClick={()=>onOpen(t.id)}><td><strong>{t.id.slice(0,12)}</strong><small>{t.prompt.slice(0,100)}</small></td><td><Badge value={t.status}/></td><td>{t.model||'Default'}</td><td>{time(t.created_at)}</td><td>{dur(t)}</td></tr>)}</tbody></table></div>}

export default function App(){
 const [page,setPage]=useState('overview'),[summary,setSummary]=useState(null),[tasks,setTasks]=useState([]),[selected,setSelected]=useState(null),[events,setEvents]=useState([]),[diagnostics,setDiagnostics]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[theme,setTheme]=useState(localStorage.getItem('agent-theme')||'dark'),[lang,setLang]=useState(localStorage.getItem('agent-lang')||'en');
 const refresh=async()=>{try{const [s,t]=await Promise.all([getDashboardSummary(),getTasks()]);setSummary(s);setTasks(t?.tasks||[]);setError('')}catch(e){setError(e.message)}};
 useEffect(()=>{refresh();const id=setInterval(refresh,5000);return()=>clearInterval(id)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.dir=lang==='fa'?'rtl':'ltr';localStorage.setItem('agent-theme',theme);localStorage.setItem('agent-lang',lang)},[theme,lang]);
 const counts=summary?.tasks?.counts||{},workers=summary?.workers?.workers||[],agent=summary?.agent||{};
 const visible=useMemo(()=>tasks.filter(t=>(filter==='all'||t.status===filter)&&(`${t.id} ${t.prompt}`).toLowerCase().includes(query.toLowerCase())),[tasks,filter,query]);
 async function openTask(id){try{const [t,e]=await Promise.all([getTask(id),getTaskEvents(id)]);setSelected(t);setEvents(e?.events||[])}catch(e){setError(e.message)}}
 async function mutate(fn,id){setBusy(true);try{await fn(id);await refresh();if(selected?.id===id)await openTask(id)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submit(e){e.preventDefault();const prompt=new FormData(e.currentTarget).get('prompt')?.toString().trim();if(!prompt)return;setBusy(true);try{await createTask({prompt});e.currentTarget.reset();await refresh();setPage('tasks')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">AI</div><div><strong>Agent Platform</strong><small>Operations Center</small></div></div><nav>{NAV.map(([k,i,l])=><button key={k} className={page===k?'active':''} onClick={()=>setPage(k)}><span>{i}</span>{l}</button>)}</nav><div className="sidebar-foot"><Badge value={summary?.system?.ready?.status}/><small>Control plane</small></div></aside>
 <main className="main"><header className="topbar"><div><span className="eyebrow">CONTROL PLANE</span><h1>{NAV.find(x=>x[0]===page)?.[2]}</h1></div><div className="top-actions"><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…"/></label><button className="icon-btn" onClick={refresh}>↻</button><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">EN</option><option value="fa">FA</option></select><select value={theme} onChange={e=>setTheme(e.target.value)}><option value="dark">Dark</option><option value="light">Light</option><option value="system">System</option></select></div></header>
 {error&&<div className="alert danger">⚠ {error}<button onClick={()=>setError('')}>×</button></div>}
 {page==='overview'&&<><form className="hero-command" onSubmit={submit}><div><span className="eyebrow">AUTONOMOUS EXECUTION</span><h2>Professional control for real agent execution.</h2><p>Backend state is the source of truth. No synthetic runtime data is shown.</p></div><div className="command-row"><input name="prompt" required placeholder="Describe a task…"/><button disabled={busy}>{busy?'Submitting…':'Run task'}</button></div></form><div className="status-strip"><Status label="System" value={summary?.system?.ready?.status}/><Status label="Agent" value={agent.status}/><Status label="Worker" value={workers[0]?.status}/><Status label="Database" value={summary?.system?.ready?.status}/></div><div className="kpis">{[['Total',counts.total],['Queued',counts.queued],['Running',counts.running],['Completed',counts.completed],['Failed',counts.failed],['Cancelled',counts.cancelled]].map(x=><div className="kpi" key={x[0]}><span>{x[0]}</span><strong>{x[1]??'—'}</strong></div>)}</div><div className="content-grid"><Card title="Recent executions"><TaskTable tasks={tasks.slice(0,8)} onOpen={openTask}/></Card><Card title="Worker health"><Workers workers={workers}/></Card></div></>}
 {page==='tasks'&&<><div className="toolbar"><div className="filters">{['all','queued','running','completed','failed','cancelled'].map(x=><button className={filter===x?'selected':''} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><form className="quick-create" onSubmit={submit}><input name="prompt" required placeholder="New task…"/><button disabled={busy}>Create</button></form></div><Card title={`${visible.length} tasks`}><TaskTable tasks={visible} onOpen={openTask}/></Card></>}
 {page==='agents'&&<Card title="Agent runtime"><Info data={{Status:agent.status,Worker:agent.worker?.worker_id,Model:agent.model||agent.worker?.model}}/></Card>}
 {page==='workers'&&<Card title="Worker monitoring"><Workers workers={workers}/></Card>}
 {page==='executions'&&<Card title="Execution history"><TaskTable tasks={tasks.filter(t=>t.started_at)} onOpen={openTask}/></Card>}
 {page==='logs'&&<Card title="Execution events"><div className="log-view">{tasks.slice(0,50).map(t=><div className="log-line" key={t.id}><time>{time(t.created_at)}</time><span>{t.id} — {t.status}</span></div>)}</div></Card>}
 {page==='monitoring'&&<div className="content-grid"><Card title="System health"><div className="health-list"><Status label="Backend" value={summary?.system?.live?.status}/><Status label="Task store" value={summary?.system?.ready?.status}/><Status label="Agent" value={agent.status}/><Status label="Worker" value={workers[0]?.status}/></div></Card><Card title="Worker telemetry"><Workers workers={workers}/></Card></div>}
 {page==='models'&&<Card title="Runtime model"><Info data={{Model:agent.model||agent.worker?.model||'Not reported',Status:agent.status||'unknown'}}/></Card>}
 {page==='tools'&&<Card title="Tool registry"><Empty>Tool permissions remain enforced by the backend execution agent. No unsafe frontend command console is exposed.</Empty></Card>}
 {page==='diagnostics'&&<Diagnostics value={diagnostics} load={async()=>{try{setDiagnostics(await getDiagnostics())}catch(e){setError(e.message)}}}/>
 {page==='settings'&&<div className="content-grid"><Card title="Appearance"><Setting label="Theme"><select value={theme} onChange={e=>setTheme(e.target.value)}><option value="dark">Dark</option><option value="light">Light</option><option value="system">System</option></select></Setting><Setting label="Language"><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="fa">فارسی</option></select></Setting></Card><Card title="Connection"><p className="muted">Backend endpoint comes from <code>VITE_API_BASE_URL</code>.</p></Card></div>}
 </main>{selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">TASK DETAIL</span><h2>{selected.id}</h2></div><button className="icon-btn" onClick={()=>setSelected(null)}>×</button></div><Badge value={selected.status}/><p className="prompt">{selected.prompt}</p><Info data={{Created:time(selected.created_at),Started:time(selected.started_at),Completed:time(selected.completed_at),Duration:dur(selected),Model:selected.model||'Default'}}/>{selected.error&&<div className="alert danger">{selected.error}</div>}<div className="timeline">{events.map((e,i)=><div key={i}><span>{time(e.timestamp||e.created_at)}</span><strong>{e.type||e.event||'event'}</strong><small>{e.message||e.detail||''}</small></div>)}</div><div className="drawer-actions">{['queued','running'].includes(selected.status)&&<button disabled={busy} onClick={()=>mutate(cancelTask,selected.id)}>Cancel</button>}{selected.status==='failed'&&<button disabled={busy} onClick={()=>mutate(retryTask,selected.id)}>Retry</button>}</div><details><summary>Execution result</summary><pre>{JSON.stringify(selected.result,null,2)}</pre></details></aside></div>}</div>
}
function Status({label,value}){return <div><span>{label}</span><Badge value={value}/></div>}
function Workers({workers}){return workers.length?workers.map(w=><div className="worker-row" key={w.worker_id}><div><strong>{w.worker_id}</strong><small>{w.host}:{w.port}</small></div><Badge value={w.status}/></div>):<Empty>No workers registered.</Empty>}
function Info({data}){return <div className="detail-grid">{Object.entries(data).map(([k,v])=><div key={k}><small>{k}</small><strong>{typeof v==='object'?JSON.stringify(v):v||'—'}</strong></div>)}</div>}
function Setting({label,children}){return <div className="setting"><span>{label}</span>{children}</div>}
function Diagnostics({value,load}){useEffect(()=>{load()},[]);return <Card title="System diagnostics"><div className="diag-list">{value?.checks?.map(c=><div key={c.name}><div><strong>{c.name}</strong><small>{typeof c.detail==='string'?c.detail:JSON.stringify(c.detail)}</small></div><Badge value={c.status}/></div>)||<Empty>Loading diagnostics…</Empty>}</div></Card>}
